"""Seed the database with sample carriers and comparison data matching the frontend."""
import uuid

from sqlalchemy.orm import Session

from app.database import SessionLocal
from app.models.models import (
    Account,
    Carrier,
    Comparison,
    ComparisonQuote,
    Property,
    Quote,
)


def seed():
    db: Session = SessionLocal()

    # Check if already seeded
    if db.query(Carrier).count() > 0:
        print("Database already seeded. Skipping.")
        db.close()
        return

    # --- Carriers ---
    carriers = {}
    carrier_data = [
        ("Travelers", "A+", "Admitted"),
        ("Zurich", "A", "Admitted"),
        ("Hartford", "A", "Admitted"),
        ("AIG", "A+", "Admitted"),
        ("Chubb", "A++", "Admitted"),
        ("CNA", "A-", "Admitted"),
    ]
    for name, rating, status in carrier_data:
        c = Carrier(carrier_name=name, am_best_rating=rating, admitted_status=status)
        db.add(c)
        db.flush()
        carriers[name] = c.id

    # --- Account ---
    acct = Account(client_name="Multi-Property Portfolio", address="Houston, TX")
    db.add(acct)
    db.flush()

    # --- Properties & Quotes ---
    properties_data = [
        {
            "address": "1234 Commerce Drive",
            "city": "Houston",
            "state": "TX",
            "zip": "77002",
            "type": "office",
            "sub_type": "Class B Multi-Tenant Office",
            "sq_footage": 45000,
            "year_built": 1995,
            "insured_value": 12000000,
            "quotes": [
                {
                    "carrier": "Travelers",
                    "quote_number": "TRV-2026-HOU-8841",
                    "quote_date": "2026-03-24",
                    "effective_date": "2026-05-01",
                    "expiry_date": "2026-04-15",
                    "building_limit": 12000000,
                    "valuation_basis": "RC",
                    "coverage_form": "Special",
                    "coinsurance": 90,
                    "bpp_limit": 500000,
                    "business_interruption_limit": 1200000,
                    "bi_period_months": 12,
                    "gl_per_occurrence": 1000000,
                    "gl_aggregate": 2000000,
                    "aop_deductible": 10000,
                    "wind_hail_deductible_pct": 2,
                    "flood_limit": 500000,
                    "equipment_breakdown": True,
                    "ordinance_or_law": False,
                    "annual_premium": 42800,
                },
                {
                    "carrier": "Zurich",
                    "quote_number": "ZNA-2026-TX-8821",
                    "quote_date": "2026-03-24",
                    "effective_date": "2026-05-01",
                    "expiry_date": "2026-04-10",
                    "building_limit": 12000000,
                    "valuation_basis": "RC",
                    "coverage_form": "Special",
                    "coinsurance": 80,
                    "bpp_limit": 500000,
                    "business_interruption_limit": 1500000,
                    "bi_period_months": 12,
                    "gl_per_occurrence": 1000000,
                    "gl_aggregate": 2000000,
                    "aop_deductible": 5000,
                    "wind_hail_deductible_pct": 2,
                    "flood_limit": None,
                    "equipment_breakdown": True,
                    "ordinance_or_law": False,
                    "annual_premium": 38500,
                    "underwriting_notes": "Flood excluded — NFIP policy strongly recommended for this Houston-area property.",
                },
                {
                    "carrier": "Hartford",
                    "quote_number": "HTFRD-2026-QT-1174",
                    "quote_date": "2026-03-24",
                    "effective_date": "2026-05-01",
                    "expiry_date": "2026-04-20",
                    "building_limit": 12000000,
                    "valuation_basis": "ACV",
                    "coverage_form": "Broad",
                    "coinsurance": 90,
                    "bpp_limit": 250000,
                    "business_interruption_limit": 1000000,
                    "bi_period_months": 12,
                    "gl_per_occurrence": 1000000,
                    "gl_aggregate": 2000000,
                    "aop_deductible": 25000,
                    "wind_hail_deductible_pct": 3,
                    "flood_limit": 250000,
                    "equipment_breakdown": False,
                    "ordinance_or_law": False,
                    "annual_premium": 31200,
                    "underwriting_notes": "ACV valuation reflects building age. RC endorsement available for +$3,800/yr. Broad form — Special form available for +$2,200/yr.",
                },
                {
                    "carrier": "AIG",
                    "quote_number": "AIG-COMM-2026-TX-9901",
                    "quote_date": "2026-03-24",
                    "effective_date": "2026-05-01",
                    "expiry_date": "2026-04-08",
                    "building_limit": 12000000,
                    "valuation_basis": "RC",
                    "coverage_form": "Special",
                    "coinsurance": 80,
                    "bpp_limit": 500000,
                    "business_interruption_limit": 1800000,
                    "bi_period_months": 12,
                    "gl_per_occurrence": 1000000,
                    "gl_aggregate": 2000000,
                    "aop_deductible": 10000,
                    "wind_hail_deductible_pct": 1,
                    "flood_limit": 1000000,
                    "equipment_breakdown": True,
                    "ordinance_or_law": True,
                    "annual_premium": 47600,
                    "underwriting_notes": "18-month BI period available by endorsement. Includes AIG Risk Management Services consultation.",
                },
            ],
        },
        {
            "address": "567 Main Street",
            "city": "Austin",
            "state": "TX",
            "zip": "78701",
            "type": "retail",
            "sub_type": "Retail Strip Mall — 8 Units",
            "sq_footage": 28000,
            "year_built": 2002,
            "insured_value": 7500000,
            "quotes": [
                {
                    "carrier": "Travelers",
                    "quote_number": "TRV-2026-AUS-4421",
                    "quote_date": "2026-03-24",
                    "effective_date": "2026-05-01",
                    "expiry_date": "2026-04-18",
                    "building_limit": 7500000,
                    "valuation_basis": "RC",
                    "coverage_form": "Special",
                    "coinsurance": 90,
                    "bpp_limit": 300000,
                    "business_interruption_limit": 800000,
                    "bi_period_months": 12,
                    "gl_per_occurrence": 1000000,
                    "gl_aggregate": 2000000,
                    "aop_deductible": 10000,
                    "wind_hail_deductible_pct": 2,
                    "flood_limit": None,
                    "equipment_breakdown": True,
                    "ordinance_or_law": False,
                    "annual_premium": 28400,
                },
                {
                    "carrier": "Zurich",
                    "quote_number": "ZNA-2026-TX-4421-R",
                    "quote_date": "2026-03-24",
                    "effective_date": "2026-05-01",
                    "expiry_date": "2026-04-12",
                    "building_limit": 7500000,
                    "valuation_basis": "RC",
                    "coverage_form": "Special",
                    "coinsurance": 80,
                    "bpp_limit": 250000,
                    "business_interruption_limit": 900000,
                    "bi_period_months": 12,
                    "gl_per_occurrence": 1000000,
                    "gl_aggregate": 2000000,
                    "aop_deductible": 5000,
                    "wind_hail_deductible_pct": 2,
                    "flood_limit": 250000,
                    "equipment_breakdown": True,
                    "ordinance_or_law": False,
                    "annual_premium": 25100,
                },
                {
                    "carrier": "Hartford",
                    "quote_number": "HTFRD-2026-QT-2281",
                    "quote_date": "2026-03-24",
                    "effective_date": "2026-05-01",
                    "expiry_date": "2026-04-22",
                    "building_limit": 7500000,
                    "valuation_basis": "RC",
                    "coverage_form": "Special",
                    "coinsurance": 90,
                    "bpp_limit": 300000,
                    "business_interruption_limit": 750000,
                    "bi_period_months": 12,
                    "gl_per_occurrence": 1000000,
                    "gl_aggregate": 2000000,
                    "aop_deductible": 15000,
                    "wind_hail_deductible_pct": 2,
                    "flood_limit": None,
                    "equipment_breakdown": False,
                    "ordinance_or_law": False,
                    "annual_premium": 22600,
                    "underwriting_notes": "Equipment breakdown excluded. Loss of rents 10-month period.",
                },
                {
                    "carrier": "Chubb",
                    "quote_number": "CHUBB-2026-TX-7731",
                    "quote_date": "2026-03-24",
                    "effective_date": "2026-05-01",
                    "expiry_date": "2026-04-28",
                    "building_limit": 7500000,
                    "valuation_basis": "RC",
                    "coverage_form": "Special",
                    "coinsurance": 80,
                    "bpp_limit": 400000,
                    "business_interruption_limit": 1000000,
                    "bi_period_months": 12,
                    "gl_per_occurrence": 2000000,
                    "gl_aggregate": 4000000,
                    "aop_deductible": 10000,
                    "wind_hail_deductible_pct": 1,
                    "flood_limit": 500000,
                    "equipment_breakdown": True,
                    "ordinance_or_law": True,
                    "annual_premium": 34200,
                },
            ],
        },
        {
            "address": "890 Industrial Pkwy",
            "city": "Dallas",
            "state": "TX",
            "zip": "75207",
            "type": "industrial",
            "sub_type": "Distribution Warehouse — Single Tenant",
            "sq_footage": 80000,
            "year_built": 2008,
            "insured_value": 15000000,
            "quotes": [
                {
                    "carrier": "Travelers",
                    "quote_number": "TRV-2026-DAL-1122",
                    "quote_date": "2026-03-24",
                    "effective_date": "2026-05-01",
                    "expiry_date": "2026-04-16",
                    "building_limit": 15000000,
                    "valuation_basis": "RC",
                    "coverage_form": "Special",
                    "coinsurance": 90,
                    "bpp_limit": 2000000,
                    "business_interruption_limit": 1500000,
                    "bi_period_months": 12,
                    "gl_per_occurrence": 1000000,
                    "gl_aggregate": 2000000,
                    "aop_deductible": 10000,
                    "wind_hail_deductible_pct": 2,
                    "flood_limit": 500000,
                    "equipment_breakdown": True,
                    "ordinance_or_law": False,
                    "annual_premium": 54200,
                },
                {
                    "carrier": "Zurich",
                    "quote_number": "ZNA-2026-TX-1122-I",
                    "quote_date": "2026-03-24",
                    "effective_date": "2026-05-01",
                    "expiry_date": "2026-04-11",
                    "building_limit": 15000000,
                    "valuation_basis": "RC",
                    "coverage_form": "Special",
                    "coinsurance": 80,
                    "bpp_limit": 1500000,
                    "business_interruption_limit": 1200000,
                    "bi_period_months": 12,
                    "gl_per_occurrence": 1000000,
                    "gl_aggregate": 2000000,
                    "aop_deductible": 10000,
                    "wind_hail_deductible_pct": 2,
                    "flood_limit": None,
                    "equipment_breakdown": True,
                    "ordinance_or_law": False,
                    "annual_premium": 48800,
                },
                {
                    "carrier": "CNA",
                    "quote_number": "CNA-2026-TX-8847",
                    "quote_date": "2026-03-24",
                    "effective_date": "2026-05-01",
                    "expiry_date": "2026-04-24",
                    "building_limit": 15000000,
                    "valuation_basis": "RC",
                    "coverage_form": "Special",
                    "coinsurance": 90,
                    "bpp_limit": 1500000,
                    "business_interruption_limit": 1000000,
                    "bi_period_months": 12,
                    "gl_per_occurrence": 1000000,
                    "gl_aggregate": 2000000,
                    "aop_deductible": 25000,
                    "wind_hail_deductible_pct": 3,
                    "flood_limit": None,
                    "equipment_breakdown": False,
                    "ordinance_or_law": False,
                    "annual_premium": 41500,
                    "underwriting_notes": "Equipment breakdown excluded. AOP deductible higher than market — reflects prior claims.",
                },
                {
                    "carrier": "AIG",
                    "quote_number": "AIG-COMM-2026-TX-4410",
                    "quote_date": "2026-03-24",
                    "effective_date": "2026-05-01",
                    "expiry_date": "2026-04-09",
                    "building_limit": 15000000,
                    "valuation_basis": "RC",
                    "coverage_form": "Special",
                    "coinsurance": 80,
                    "bpp_limit": 2500000,
                    "business_interruption_limit": 2000000,
                    "bi_period_months": 12,
                    "gl_per_occurrence": 1000000,
                    "gl_aggregate": 2000000,
                    "aop_deductible": 10000,
                    "wind_hail_deductible_pct": 2,
                    "flood_limit": 1000000,
                    "equipment_breakdown": True,
                    "ordinance_or_law": True,
                    "annual_premium": 62400,
                },
            ],
        },
        {
            "address": "234 Urban Center Blvd",
            "city": "Chicago",
            "state": "IL",
            "zip": "60601",
            "type": "mixed-use",
            "sub_type": "Mixed-Use — Office 60% + Retail 40%",
            "sq_footage": 35000,
            "year_built": 2015,
            "insured_value": 10000000,
            "quotes": [
                {
                    "carrier": "Travelers",
                    "quote_number": "TRV-2026-CHI-3310",
                    "quote_date": "2026-03-24",
                    "effective_date": "2026-05-01",
                    "expiry_date": "2026-04-17",
                    "building_limit": 10000000,
                    "valuation_basis": "RC",
                    "coverage_form": "Special",
                    "coinsurance": 90,
                    "bpp_limit": 400000,
                    "business_interruption_limit": 1000000,
                    "bi_period_months": 12,
                    "gl_per_occurrence": 1000000,
                    "gl_aggregate": 2000000,
                    "aop_deductible": 10000,
                    "wind_hail_deductible_pct": 2,
                    "flood_limit": 500000,
                    "equipment_breakdown": True,
                    "ordinance_or_law": False,
                    "annual_premium": 38600,
                },
                {
                    "carrier": "Zurich",
                    "quote_number": "ZNA-2026-IL-3310-M",
                    "quote_date": "2026-03-24",
                    "effective_date": "2026-05-01",
                    "expiry_date": "2026-04-14",
                    "building_limit": 10000000,
                    "valuation_basis": "RC",
                    "coverage_form": "Special",
                    "coinsurance": 80,
                    "bpp_limit": 400000,
                    "business_interruption_limit": 1200000,
                    "bi_period_months": 12,
                    "gl_per_occurrence": 1000000,
                    "gl_aggregate": 2000000,
                    "aop_deductible": 5000,
                    "wind_hail_deductible_pct": 2,
                    "flood_limit": None,
                    "earthquake_limit": 1000000,
                    "equipment_breakdown": True,
                    "ordinance_or_law": False,
                    "annual_premium": 34200,
                },
                {
                    "carrier": "Hartford",
                    "quote_number": "HTFRD-2026-QT-3310",
                    "quote_date": "2026-03-24",
                    "effective_date": "2026-05-01",
                    "expiry_date": "2026-04-23",
                    "building_limit": 10000000,
                    "valuation_basis": "ACV",
                    "coverage_form": "Special",
                    "coinsurance": 90,
                    "bpp_limit": 300000,
                    "business_interruption_limit": 900000,
                    "bi_period_months": 12,
                    "gl_per_occurrence": 1000000,
                    "gl_aggregate": 2000000,
                    "aop_deductible": 15000,
                    "wind_hail_deductible_pct": 2,
                    "flood_limit": 250000,
                    "equipment_breakdown": False,
                    "ordinance_or_law": False,
                    "annual_premium": 29800,
                    "underwriting_notes": "ACV valuation. RC endorsement available +$3,200/yr.",
                },
                {
                    "carrier": "AIG",
                    "quote_number": "AIG-COMM-2026-TX-3310-MX",
                    "quote_date": "2026-03-24",
                    "effective_date": "2026-05-01",
                    "expiry_date": "2026-04-07",
                    "building_limit": 10000000,
                    "valuation_basis": "RC",
                    "coverage_form": "Special",
                    "coinsurance": 80,
                    "bpp_limit": 500000,
                    "business_interruption_limit": 1400000,
                    "bi_period_months": 18,
                    "gl_per_occurrence": 1000000,
                    "gl_aggregate": 2000000,
                    "aop_deductible": 10000,
                    "wind_hail_deductible_pct": 1,
                    "flood_limit": 750000,
                    "equipment_breakdown": True,
                    "ordinance_or_law": True,
                    "annual_premium": 43100,
                },
            ],
        },
    ]

    comparisons_meta = [
        ("Commerce Drive Partners LLC", "Sarah Mitchell"),
        ("Main Street Retail Group", "Sarah Mitchell"),
        ("Industrial Pkwy Warehouse LLC", "Sarah Mitchell"),
        ("Urban Center Properties Inc", "Sarah Mitchell"),
    ]

    for idx, prop_data in enumerate(properties_data):
        quotes_data = prop_data.pop("quotes")
        prop = Property(account_id=acct.id, **prop_data)
        db.add(prop)
        db.flush()

        quote_ids = []
        for qd in quotes_data:
            carrier_name = qd.pop("carrier")
            q = Quote(
                property_id=prop.id,
                carrier_id=carriers[carrier_name],
                **qd,
            )
            db.add(q)
            db.flush()
            quote_ids.append(q.id)

        # Create comparison
        client_name, producer = comparisons_meta[idx]
        comp = Comparison(
            account_id=acct.id,
            client_name=client_name,
            producer=producer,
        )
        db.add(comp)
        db.flush()

        for order, qid in enumerate(quote_ids):
            cq = ComparisonQuote(comparison_id=comp.id, quote_id=qid, display_order=order)
            db.add(cq)

    db.commit()
    db.close()
    print("Database seeded successfully with sample data!")


if __name__ == "__main__":
    seed()
